Deploy automatically to cloud run

diff --git a/.buildkite/deploy-production b/.buildkite/deploy-production
--- a/.buildkite/deploy-production
+++ b/.buildkite/deploy-production
@@ -12,25 +12,27 @@ fi
 manifest="$(mktemp)"
 echo '--- :kubernetes: Shipping'
 gcloud config set project banba-group
-gcloud container clusters get-credentials production --zone us-central1-a
-envsubst < k8s/production/deployment.yaml > "${manifest}"
-kubectl apply -f "${manifest}"
+gcloud run deploy vayu-com-au --image $DOCKER_IMAGE --region us-central1
 
-echo '--- :zzz: Waiting for deployment'
-#kubectl wait --for condition=available --timeout=150s -f "${manifest}"
+# gcloud container clusters get-credentials production --zone us-central1-a
+# envsubst < k8s/production/deployment.yaml > "${manifest}"
+# kubectl apply -f "${manifest}"
 
-ATTEMPTS=0
-ROLLOUT_STATUS_CMD="kubectl rollout status deployment vayu-com-au --namespace=www-vayu-com-au"
-until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 100 ]; do
-    $ROLLOUT_STATUS_CMD
-    ATTEMPTS=$((attempts + 1))
-    echo "."
-    sleep 10
-done
+# echo '--- :zzz: Waiting for deployment'
+# #kubectl wait --for condition=available --timeout=150s -f "${manifest}"
 
-if ! kubectl rollout status deployment vayu-com-au --namespace=www-vayu-com-au; then
-    echo "Failed to deploy; rolling back the deployment"
-    kubectl rollout undo deployment vayu-com-au --namespace=www-vayu-com-au
-    kubectl rollout status deployment vayu-com-au --namespace=www-vayu-com-au
-    exit 1
-fi
+# ATTEMPTS=0
+# ROLLOUT_STATUS_CMD="kubectl rollout status deployment vayu-com-au --namespace=www-vayu-com-au"
+# until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 100 ]; do
+#     $ROLLOUT_STATUS_CMD
+#     ATTEMPTS=$((attempts + 1))
+#     echo "."
+#     sleep 10
+# done
+
+# if ! kubectl rollout status deployment vayu-com-au --namespace=www-vayu-com-au; then
+#     echo "Failed to deploy; rolling back the deployment"
+#     kubectl rollout undo deployment vayu-com-au --namespace=www-vayu-com-au
+#     kubectl rollout status deployment vayu-com-au --namespace=www-vayu-com-au
+#     exit 1
+# fi
